### ISSUE TITLE
Doesn't work for me (1.8)

### ISSUE THREAD

**Issue by JanJastrow** [J3FF97/YASM#1]
Yes, I know this is a terrible description, but I don't know anything about reporting minecraft forge plugin errors.
But still, here is the crash report:
http://pastie.org/10192321

Maybe it tells you something :)

**Comment by J3FF97** [comment]
This... Is a special one.. If I'm not misstaken it's baaaasically telling me it can't find the base Minecraft class, which is strange. Especially since it does work on all my machines. I checked your log and you are using the same version of Forge as I used to build. So next question. What MC version are you using? 1.8 or 1.8.\* ? I'll run some tests and see if I can reproduce anything like that. 

To be continued.

**Comment by JanJastrow** [comment]
I'm using 1.8.
Will deliver logfiles on your demand. :+1:
